### ISSUE TITLE
What is the source of the dataset?

### ISSUE THREAD

**Issue by OmarHedeya95** [haresrv/Dustbin#1]
Hey Hare,
Thanks a lot for this really cool project. I just wanted to ask if you would please share the source of your dataset?

**Comment by haresrv** [comment]
Hi Omar, Thanks for checking out my project. 
I've made the dataset public. You can access it at [Kaggle Link](https://www.kaggle.com/haresrv/amazonreview) 
I don't know the authenticity of dataset. I got it from some other website long back.

**Comment by OmarHedeya95** [comment]
Thanks a lot
